### ISSUE TITLE
Contribute to the Bytecode Alliance (Tracking Issue)

### ISSUE THREAD

**Issue by esoterra** [esoterra/wow#7]
This issue is a public commitment to donate the `wow` project to the Bytecode Alliance at the point where it is ready to be [proposed](https://github.com/bytecodealliance/governance/blob/main/templates/projects/proposal.md).

I have no idea when that will be since donation requires that goals, governance, and materials are mature enough and that may take some time.

I will track the steps required to prepare the project for donation here:

- [ ] Write up the project and it's goals
- [ ] Create basic documentation
- [ ] Write up a basic governance structure
- [ ] Define the software development process
- [ ] Identify supporting members
